"""empty message

Revision ID: 29301e3521fb
Revises: 6b448d274561
Create Date: 2024-04-07 10:34:31.276014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29301e3521fb'
down_revision = '6b448d274561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sobrenome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
